services:
  - type: web
    name: gencat-records-management
    env: python
    plan: free
    branch: main
    healthCheckPath: /healthcheck
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --config gunicorn_config.py wsgi:app"
    envVars:
      - fromGroup: gencat-settings
      - key: DATABASE_URL
        fromDatabase:
          name: gencat-db
          property: connectionString

envVarGroups:
  - name: gencat-settings
    envVars:
      - key: ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: gencat-db
    plan: free
    databaseName: gencat
