"""rename user id to userID; add all domain tables

Revision ID: 78fa44e34295
Revises: 68e6659b6ca9
Create Date: 2026-03-05 00:01:45.890208

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78fa44e34295"
down_revision = "68e6659b6ca9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("locationID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("geoLocation", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("locationID"),
    )
    op.create_table(
        "box",
        sa.Column("boxID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bayNo", sa.Integer(), nullable=False),
        sa.Column("rowNo", sa.Integer(), nullable=False),
        sa.Column("columnNo", sa.Integer(), nullable=False),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("locationID", sa.Integer(), nullable=False),
        sa.Column("colorStatus", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["locationID"],
            ["location.locationID"],
        ),
        sa.PrimaryKeyConstraint("boxID"),
        sa.UniqueConstraint("barcode"),
    )
    op.create_table(
        "patron",
        sa.Column("patronID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userID", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userID"],
            ["user.userID"],
        ),
        sa.PrimaryKeyConstraint("patronID"),
    )
    op.create_table(
        "staff_user",
        sa.Column("staffUserID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userID", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userID"],
            ["user.userID"],
        ),
        sa.PrimaryKeyConstraint("staffUserID"),
    )
    op.create_table(
        "loan",
        sa.Column("loanID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("loanDate", sa.DateTime(), nullable=False),
        sa.Column("returnDate", sa.DateTime(), nullable=True),
        sa.Column("processedByStaffUserID", sa.Integer(), nullable=True),
        sa.Column("patronID", sa.Integer(), nullable=False),
        sa.Column("damageNotes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="Active",
        ),
        sa.ForeignKeyConstraint(
            ["patronID"],
            ["patron.patronID"],
        ),
        sa.ForeignKeyConstraint(
            ["processedByStaffUserID"],
            ["staff_user.staffUserID"],
        ),
        sa.PrimaryKeyConstraint("loanID"),
    )
    op.create_table(
        "file",
        sa.Column("fileID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("boxID", sa.Integer(), nullable=False),
        sa.Column("locationID", sa.Integer(), nullable=True),
        sa.Column("loanID", sa.Integer(), nullable=True),
        sa.Column("fileType", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("previousDesignation", sa.String(length=255), nullable=True),
        sa.Column("createdByStaffUserID", sa.Integer(), nullable=True),
        sa.Column("dateCreated", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("conditionNotes", sa.Text(), nullable=True),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["boxID"],
            ["box.boxID"],
        ),
        sa.ForeignKeyConstraint(
            ["createdByStaffUserID"],
            ["staff_user.staffUserID"],
        ),
        sa.ForeignKeyConstraint(
            ["loanID"],
            ["loan.loanID"],
        ),
        sa.ForeignKeyConstraint(
            ["locationID"],
            ["location.locationID"],
        ),
        sa.PrimaryKeyConstraint("fileID"),
        sa.UniqueConstraint("barcode"),
    )
    op.create_table(
        "staff_record",
        sa.Column("staffRecordID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fileNumber", sa.String(length=100), nullable=True),
        sa.Column("fileTitle", sa.String(length=255), nullable=True),
        sa.Column("post", sa.String(length=255), nullable=True),
        sa.Column("organisationUnit", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("fileID", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fileID"],
            ["file.fileID"],
        ),
        sa.PrimaryKeyConstraint("staffRecordID"),
    )
    op.create_table(
        "student",
        sa.Column("studentID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("certificateDiploma", sa.String(length=255), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=True),
        sa.Column("fileID", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fileID"],
            ["file.fileID"],
        ),
        sa.PrimaryKeyConstraint("studentID"),
    )
    # Add userType column to user table (exists in model but was not in initial migration)
    with op.batch_alter_table("user") as batch_op:
        batch_op.add_column(
            sa.Column(
                "userType",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_column("userType")
    op.drop_table("student")
    op.drop_table("staff_record")
    op.drop_table("file")
    op.drop_table("loan")
    op.drop_table("staff_user")
    op.drop_table("patron")
    op.drop_table("box")
    op.drop_table("location")
    # ### end Alembic commands ###
